### ISSUE TITLE
Linux build failure.

### ISSUE THREAD

**Issue by orbea** [libretro/fmsx-libretro#16]
OS: `Slaclware64-current`
`gcc-7.1.0`

fmsx-libretro fails to build.
```
cc -c -o EMULib/SHA1.o EMULib/SHA1.c -DGIT_VERSION=\"" f958fe3"\" -O3 -fPIC -D__LIBRETRO__  -DUNIX -DFMSX -DBPS16 -DBPP16  -I. -I./libretro-common/include -I./EMULib -I./Z80 -I./fMSX 
libretro.c: In function ‘check_variables’:
libretro.c:475:4: error: ‘ModeRAM’ undeclared (first use in this function); did you mean ‘ModeYAE’?
    ModeRAM = 0;
    ^~~~~~~
    ModeYAE
libretro.c:475:4: note: each undeclared identifier is reported only once for each function it appears in
libretro.c:476:4: error: ‘ModeVRAM’ undeclared (first use in this function); did you mean ‘ModeRAM’?
    ModeVRAM = 0;
    ^~~~~~~~
    ModeRAM
libretro.c:484:7: error: expected ‘}’ before ‘else’
       else if (strcmp(var.value, "MSX2") == 0)
       ^~~~
libretro.c:488:7: error: ‘else’ without a previous ‘if’
       else if (strcmp(var.value, "MSX2+") == 0)
       ^~~~
libretro.c: At top level:
libretro.c:493:4: error: expected identifier or ‘(’ before ‘else’
    else
    ^~~~
libretro.c:500:7: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘.’ token
    var.key = "fmsx_video_mode";
       ^
libretro.c:501:7: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘.’ token
    var.value = NULL;
       ^
libretro.c:503:4: error: expected identifier or ‘(’ before ‘if’
    if (environ_cb(RETRO_ENVIRONMENT_GET_VARIABLE, &var) && var.value)
    ^~
libretro.c:510:4: error: expected identifier or ‘(’ before ‘else’
    else
    ^~~~
libretro.c:515:7: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘.’ token
    var.key = "fmsx_mapper_type_mode";
       ^
libretro.c:516:7: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘.’ token
    var.value = NULL;
       ^
libretro.c:518:4: error: expected identifier or ‘(’ before ‘if’
    if (environ_cb(RETRO_ENVIRONMENT_GET_VARIABLE, &var) && var.value)
    ^~
libretro.c:525:4: error: expected identifier or ‘(’ before ‘else’
    else
    ^~~~
libretro.c:530:7: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘.’ token
    var.key = "fmsx_ram_pages";
       ^
libretro.c:531:7: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘.’ token
    var.value = NULL;
       ^
libretro.c:533:4: error: expected identifier or ‘(’ before ‘if’
    if (environ_cb(RETRO_ENVIRONMENT_GET_VARIABLE, &var) && var.value)
    ^~
libretro.c:546:4: error: expected identifier or ‘(’ before ‘else’
    else
    ^~~~
libretro.c:551:7: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘.’ token
    var.key = "fmsx_vram_pages";
       ^
libretro.c:552:7: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘.’ token
    var.value = NULL;
       ^
libretro.c:554:4: error: expected identifier or ‘(’ before ‘if’
    if (environ_cb(RETRO_ENVIRONMENT_GET_VARIABLE, &var) && var.value)
    ^~
libretro.c:567:4: error: expected identifier or ‘(’ before ‘else’
    else
    ^~~~
libretro.c:571:1: error: expected identifier or ‘(’ before ‘}’ token
 }
 ^
cc -c -o EMULib/Floppy.o EMULib/Floppy.c -DGIT_VERSION=\"" f958fe3"\" -O3 -fPIC -D__LIBRETRO__  -DUNIX -DFMSX -DBPS16 -DBPP16  -I. -I./libretro-common/include -I./EMULib -I./Z80 -I./fMSX 
make: *** [Makefile:246: libretro.o] Error 1
make: *** Waiting for unfinished jobs....
```
Bisect.
```
934594234e299ac121955f5214b81b300cf57521 is the first bad commit
commit 934594234e299ac121955f5214b81b300cf57521
Author: Matt Sephton <matt.sephton@gmail.com>
Date:   Mon Jun 26 16:43:38 2017 +0100

    exposed RAMPages and VRAMPages settings

:100644 100644 0eb88bb330a2e9bd21e45b1905f6e9ecd99f71d5 6b0fcd7d0eeb4ed01a5ed214b1f2d1ec53ee1f89 M	libretro.c
```
934594234e299ac121955f5214b81b300cf57521

Build failure on the initial bad commit, it has since gotten worse as seen above.
```
cc -o fmsx_libretro.so -shared -Wl,-version-script=link.T -Wl,-no-undefined ./libretro.o ./EMULib/EMULib.o ./EMULib/Sound.o ./fMSX/MSX.o ./fMSX/V9938.o ./fMSX/I8251.o ./EMULib/SHA1.o ./EMULib/Floppy.o ./EMULib/FDIDisk.o ./Z80/Z80.o ./EMULib/I8255.o ./EMULib/YM2413.o ./EMULib/AY8910.o ./EMULib/SCC.o ./EMULib/WD1793.o ./libretro-common/file/retro_dirent.o 
./libretro.o: In function `check_variables':
libretro.c:(.text+0x5115): undefined reference to `strcp'
collect2: error: ld returned 1 exit status
make: *** [Makefile:263: fmsx_libretro.so] Error 1
```

**Comment by gingerbeardman** [comment]
See pull #17

**Comment by orbea** [comment]
You can't just type `make` to build the core?

**Comment by ensrha** [comment]
>I can still not build the cores, please also see libretro/libretro-super#475

Isn't that because you didn't change "strcp" to "strcmp" in libretro.c

**Comment by gingerbeardman** [comment]
Oh dear, thanks for spotting that!
